export const data = [
    {
        id: 1,
        image: 'https://cdn.pixabay.com/photo/2020/01/16/13/34/positano-4770578_1280.jpg',
        country: 'Italia',
        city: 'Positano',
        discribtion: 'Positano var tidligere en viktig del av en mektig sjømakt, og i dag er den en sofistikert ferieby og juvelen i den ikoniske Amalfikysten i sør-Italia. Bratte åser dekket av gågater og søtduftende blåregn vender ut mot Sirenuse-øyene. Landsbyen er hjem til mange lekre boutiquer som selger keramikk pyntet med sitroner og håndlagde lærsandaler. Prøv den ferske sjømaten og de lokale vinene ved byens utallige romantiske restauranter. Positano er også en flott base for å utforske området videre du kan enkelt reise med båt til Capri, Ischia og Grotta dello Smeraldo.',  
    },
    {
        id: 2,
        image: 'https://cdn.pixabay.com/photo/2021/02/28/18/08/cascais-6057892_1280.jpg',
        country: 'Portugal',
        city: 'Cascais',
        discribtion: 'Kystbyen Cascais bare 28 km vest for Lisboa var én gang en liten fiskerlandsby, men de idylliske omgivelsene fanget oppmerksomheten til kunstnere, forfattere og utstøtt europeisk adel i det 20. århundre. Den tiltrekker seg fremdeles sosieteten, men alle lag kommer med full styrke for å nyte de vakre strendene og seile og surfe. Museet Conde de Castro Guimarães Museum, et tidligere palass, er nå åpent for publikum og har en imponerende samling av kunst og kunstgjenstander.',    
    },
    {
        id: 3,
        image: 'https://cdn.pixabay.com/photo/2017/10/27/10/14/krakow-2893783_1280.jpg',
        country: 'Polen',
        city: 'Krakow',
        discribtion: 'Wawel-slottet, Kazimierz-distriktet, Mariakirken og hovedtorget ... Kraków ble lagt inn i den første av UNESCOs lister over verdens kultur- og naturarvsteder og tilbyr et vell av historie og arkitektur. Byen som i århundrer har blitt verdsatt for sin kulturarv, har også blitt et europeisk senter for gastronomisk matkultur. I 2019 ble Kraków tildelt tittelen europeisk hovedstad for gastronomisk kultur av European Academy of Gastronomy. I Kraków er det et yrende kulturliv. Hvert år er hovedstaden i Lille-Polen vertskap for nærmere 100 festivaler og andre internasjonale arrangementer.',   
    },
    {
        id: 4,
        image: 'https://cdn.pixabay.com/photo/2021/07/25/12/22/town-6491733_1280.jpg',
        country: 'Tyskland',
        city: 'Rothenburg ob der Tauber',
        discribtion: 'Etter bare ytterligere 220 trinn nås målet og belønningen er fantastisk. Fra tårnet til rådhuset kan du se den pittoreske Tauber-dalen og Rothenburgs middelalderske gamleby, i all sin prakt: kirkene, de helt intakte bymurene, gangbare i to kilometer, og torget som folk går på vei til Plönlein, Crime Museum eller tårnveien. Rett under utsiktsplattformen har en stork tatt stilling på taket av rådhuset.',   
    },  
    {
        id: 5,
        image: 'https://cdn.pixabay.com/photo/2021/05/18/08/07/buildings-6262595_1280.jpg',
        country: 'Sveits',
        city: 'Bern',
        discribtion: 'Betraktet som en av verdens byer med den beste livskvaliteten, Bern, hovedstaden i Sveits, er en av de store middelalderske og kosmopolitiske juvelene i Europa. Omgitt for en stor del av det blå beltet som danner Aare-elven, gamlebyen eller gamlebyen i Bern er den eldste utheve fra hovedstaden i Sveits. Etter å ha fått tilgang til en av steinbroene som forbinder den med resten av byen, er den gamle delen av Bern muligens en av beste eksemplene på middelalderbyplanlegging fra hele Europa Takket være estetikken som er bevart siden 1191, året den ble grunnlagt av Berchtold V, og at den, til tross for den store brannen som herjet byen på XNUMX-tallet, ble fullstendig gjenoppbygd kort tid etter. "The Collegiate Church", som sveitserne også kaller det, er en annen av de store stoltheter i byen. Byggingen begynte i 1421 til ære for skytshelgen Saint Vincent av Zaragoza, selv om konstruksjonen ble nådd opp til 60 meter i høyden for å kontrollere fundamentet. Etter flere renoveringer ble katedralen endelig fullført og viste seg 100 meter tårnet som flagrer over hustakene i gamlebyen. I gotisk stil skjuler Bern-katedralen i sine indre dyrebare hvelv som vil glede elskere av hellig kunst.',    
    },
    {
        id: 6,
        image: 'https://cdn.pixabay.com/photo/2014/04/26/10/02/parc-guell-332390_1280.jpg',
        country: 'Spania',
        city: 'Barcelona',
        discribtion: 'Barcelona er en by og provins som ligger i det autonome samfunnet Catalonia. Den nest mest befolkede byen i hele Spania holder også mange hemmeligheter. La Sagrada Familia er et av de første punktene som vi ikke bør gå glipp av å besøke. Et verk av Gaudí som startet i 1883. ',    
    },
    {
        id: 7,
        image: 'https://cdn.pixabay.com/photo/2017/10/18/14/54/london-eye-2864410_1280.jpg',
        country: 'England',
        city: 'London',
        discribtion: 'London er by full av historie, der det middelalderske og viktorianske utfyller en rik og levende moderne verden. Tower of London og Westminster ligger nær lokale nabopuber og markeder, og tidsslitte ritualer, som endring av vaktene, finner sted mens pendlerne haster for å rekke «the Tube». Det er et sted der reisende kan reise i tid gjennom byen. Og når de er slitne, kan de gjør som de som bor der, og ta seg en «cuppa tea».',    
    },
    {
        id: 8,
        image: 'https://cdn.pixabay.com/photo/2017/03/04/04/29/bruges-2115481_1280.jpg',
        country: 'Belgia',
        city: 'Brugge',
        discribtion: 'Hva kan være mer romantisk og inspirerende enn et sted som ser ut som omgivelsene for et eventyr? Det hviler en middelaldersk atmosfære over Brugges brusteinsgater, og de fører til utallige historiske, arkitektoniske og kunstneriske praktverk. Nyt synet av rikt ornamenterte hus langs intrikate kanaler, og du skjønner hvorfor dette er et yndet mål for alle slags reisende. Hele byen utstråler en verdsettelse av fortiden, en kjærlighet til samtiden og en entusiasme for framtiden. Få med deg Hof Bladelin, Groeninge Museum, Vår Frues kirke og Belfort (klokketårnet) og torghallene.',   
    },
    {
        id: 9,
        image: 'https://cdn.pixabay.com/photo/2019/08/28/13/26/iceland-4436790_1280.jpg',
        country: 'Island',
        city: 'Reykjavik',
        discribtion: 'Iskalotter og isbreer, sprutende geysirer og dampende svovelkratre, vulkaner, ville elver og prektige fosser, flokker av lundefugler og alker, og hvaler som stiger opp til overflaten like utenfor kysten – dette er bare en helt vanlig dag på Island. Landets mange geologiske underverk har ført til en turistboom, med mange førstegangsbesøkende som kjører den gylne sirkelen sørvestover. Livlige Reykjavik har en rekke menneskeskapte attraksjoner også, som den majestetiske Hallgrimskirkja og en musikkscene som aldri gir opp. Varme kilder er også et stort trekkplaster, som for eksempel mineralrike Den blå lagune.',    
    },
    {
        id: 10,
        image: 'https://cdn.pixabay.com/photo/2019/08/19/15/13/eiffel-tower-4416700_1280.jpg',
        country: 'Frankrike',
        city: 'Paris',
        discribtion: 'Ingen andre steder på jorden får hjertet til å slå som når du nevner Paris. Byen lokker med sin praktfulle kunst, arkitektur, kultur og mat, men det er også en roligere magi som venter på å bli utforsket: de sjarmerende brosteinsbelagte gatene, de søte konditorene rundt hjørnet og de koselige, små bistroene som lokker med et glass Beaujolais. Gjør deg klar til å gjøre Paris til din egen.',    
    },
    {
        id: 11,
        image: 'https://cdn.pixabay.com/photo/2018/12/06/11/45/tirana-3859645_1280.jpg',
        country: 'Albania',
        city: 'Tirana',
        discribtion: 'Hovedstaden i Albania er et av de beste stedene når det gjelder å komme inn i dette unike landet på Balkan. Tirana er omgitt av åser, daler og Adriaterhavet Skanderberg-plassen, full av hager og de viktigste administrative bygningene i byen, i tillegg til andre monumenter som Et`hem Bey-moskeen, ren kontrast, eller Pyramiden i Tirana, for tiden et konferansesenter med et mest særegent design. En unik by hvis beste måte å skimte på en panoramisk måte er gjennom en taubanevei til toppen av Mount Dajt.',    
    },
    {
        id: 12,
        image: 'https://cdn.pixabay.com/photo/2018/12/04/09/06/ljubljana-3855145_1280.jpg',
        country: 'Slovenia',
        city: 'Ljubljana',
        discribtion: 'Slovenia, wedged between Austria and Italy, has always been proud of its unique heritage. The capital, Ljubljana, is a perfect example of this blend of German, Mediterranean, and Slovenian culture...',    
    },
    {
        id: 13,
        image: 'https://cdn.pixabay.com/photo/2016/10/05/14/11/work-of-art-1716745_1280.jpg',
        country: 'Nord-Irland',
        city: 'Belfast',
        discribtion: 'Belfast har vokst til en verdensby med nesten 300 000 innbyggere, og har blitt et populært reisemål for weekendturer. Med optimisme og liv som pulserer gjennom byen, er Belfast et stimulerende reisemål. Det har aldri vært enklere å komme seg rundt i byen, takket være en rekke interessante muligheter med buss, taxi og båt og til fots. Du bør ikke gå glipp av Ulster folkemuseum eller Belfast-katedralen, og noen av de prisbelønte restaurantene, barene, klubbene, galleriene og teatrene er flotte opplevelser.',    
    },
    {
        id: 14,
        image: 'https://images.pexels.com/photos/4377310/pexels-photo-4377310.jpeg',
        country: 'Ungarn',
        city: 'Budapest',
        discribtion: 'Budapest er hovedstaden i Ungarn og en av de mest befolkede byene i det sentral- og østeuropeiske området. Men i tillegg til befolkningen, må det sies at mange er enige om at det er et av de vakreste stedene i hele Europa. Selvfølgelig, hvis du fremdeles ikke anser det slik, må du bare oppdage følgende.',    
    },
    {
        id: 15,
        image: 'https://cdn.pixabay.com/photo/2019/05/08/22/01/helsinki-cathedral-4189825_1280.jpg',
        country: 'Finland',
        city: 'Helsingfors',
        discribtion: 'Helsingfors ligger sør i landet, og er hovedstaden og den viktigste byen i Finland. Det er også en kystby som gir navn til en skjærgård på nesten tre hundre øyer og som kan skryte bærekraft, i stor grad takket være de store grøntområdene. Den har et storbyområde på omtrent en million fire hundre tusen innbyggere, til tross for at tempoet i livet er rolig.',    
    },
    {
        id: 16,
        image: 'https://cdn.pixabay.com/photo/2015/10/16/10/27/edinburgh-990922_1280.jpg',
        country: 'Skottland',
        city: 'Edinburg',
        discribtion: 'Edinburgh, Skottlands hovedstad, er kjent for sin historie, sin kultur og sine festivaler. Ta en lang gåtur i sentrum for å utforske verdensarvstedene Old Town og New Town, samt områdets mange museer og gallerier. Ta en pause for å styrke deg på te og scones i byens sjarmerende terom, eller ta en tur innom en tradisjonell pub. Deretter kan du tar turen til et av Edinburghs mange arrangementer – inkludert de berømte kulturelle sommerfestivalene, eller vinterfestivaler som er fulle av musikk, lys og cèilidh-er. Det er den nest mest besøkte av turister fra den fremmede byen som ligger på østkysten av Skottland, i en avstand på omtrent 47 kilometer fra Glasgow og 332 kilometer fra London.',    
    },
    {
        id: 17,
        image: 'https://cdn.pixabay.com/photo/2016/07/26/21/43/vienna-1544009_1280.jpg',
        country: 'Øsrerrike',
        city: 'Wien',
        discribtion: 'I Wien er ikke kaffehusene bare et møtested, de er en institusjon. Å lese avisen med et bakverk og en sterk espressodrikk er ifølge UNESCO en offisiell hjørnestein i wienersk kultur. Gå av deg kakestykket med Sachertorte gjennom en selvguidet rundtur for å se byens storslagne tradisjonelle, separatistiske og moderne arkitektur, som keiserpalasset, den statlige operaen, Kirche am Steinhof eller det kunsthistoriske museum, som er en øvelse i dekorativ geometri.',
    },
    {
        id: 18,
        image: 'https://cdn.pixabay.com/photo/2017/09/29/15/46/amsterdam-2799491_1280.jpg',
        country: 'Holland',
        city: 'Amsterdam',
        discribtion: 'Amsterdam er en ekte eventyrverden med sine billedskjønne kanaler, broer og historiske bygg. De fargerike syklene og tulipanene rundt om i byen hjelper også. Severdigheter inkluderer huset til Anne Frank, Van Gogh-museet og verdens eneste flytende blomstermarked. Hvorfor ikke leie en sykkel for bli ett med lokalbefolkningen? Andre besøkende ønsker kanskje å kose seg i den lokale kaffebaren, en kjent og kjær del av byens dagligliv.',    
    },
    {
        id: 19,
        image: 'https://cdn.pixabay.com/photo/2013/08/29/08/24/st-peters-square-177011_1280.jpg',
        country: 'Hellas',
        city: 'Athen',
        discribtion: 'Helt siden neolittisk tid har Aten vært hjertet til en av verdens mest utrolige sivilisasjoner, dominert av kolossale, arkitektoniske detaljer fra den eldgamle fortiden, fra Akropolis til Zevs-tempelet. Nabolagene og bakgatene i Aten, derimot, viser sin vakre, moderne og avslappende energi, med livlige, urbane restauranter og tøffe gallerier, med relikvier fra en svunnen tid som bakteppe. Hvis du leter etter pusterom fra det travle livet, kan du ta en spasertur ned til den skinnende kystlinjen, med uberørte farvann og avslappede strandferiesteder.',    
    },
    {
        id: 20,
        image: 'https://images.pexels.com/photos/7346980/pexels-photo-7346980.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        country: 'Romania',
        city: 'Bucuresti',
        discribtion: 'Bucuresti har fått kallenavnet “Lille Paris” på grunn av den franske innflytelsen på den elegante arkitekturen fra tidlig i det 20. århundre. Ikke gå glipp av landsbymuseet, rumensk ateneum og bondemuseet. Du må også få med deg parlamentpalasset, den nest største bygningen i verden (etter Pentagon).',    
    },
]